### ISSUE TITLE
.exe execution

### ISSUE THREAD

**Issue by Yanrs** [undefined-sin/wvsapp#2]
I know that your code only cover the .dll but can you help me to execute the .exe files?
I'm getting an error when I try to execute it.
![image](https://user-images.githubusercontent.com/7788650/52179111-503d2f00-27bd-11e9-826b-b87a2d00ec56.png)

**Comment by undefined-sin** [comment]
It's hard to tell what is exactly the error, but it probably is a configuration file issue or a missing database query. 

Try to use IDA to debug the binary to find exactly the source of the problem or check the logs under C:\MSLog

**Comment by Yanrs** [comment]
I'm sorry, I'm really a newbie on reverse engineering and working with this kind of files.
Let me start by saying what I did so far and I would like to request your help to show me what I missed and what else I need to do to get the whole thing up and running.
1_Got the svr and client files 
2_Compiled your project
3_Replaced the dlls both in svr and client

What I believe is pending: Set up the database and execute the server files

**Comment by undefined-sin** [comment]
Setting up the database is not a easy task. You have to reverse engineer the whole structure and re-implement all the procedures. 
Take a look into ragezone and check the last version that someone posted and then use SQL profiler to debug the database queries. 
To find out what parameters the queries / procedures accept you should use IDA.
